# Generated by Django 3.2.5 on 2021-08-09 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev', models.IntegerField(max_length=4)),
                ('ho', models.IntegerField(max_length=2)),
                ('nap', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Foglalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oraszam', models.IntegerField(max_length=1)),
                ('mennyiseg', models.IntegerField(max_length=2)),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletadminapp.nap')),
            ],
        ),
    ]
