# Generated by Django 3.2.5 on 2021-08-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletadminapp', '0002_auto_20210809_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kornyezeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elerhetotablet', models.IntegerField()),
                ('napioraszam', models.IntegerField()),
            ],
        ),
    ]
