# Generated by Django 3.2.5 on 2021-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletadminapp', '0004_kornyezeti_alap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foglalas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
